#This is the name of the service
service: aws-lambda-fastapi

#This is the common serverless config of the project
provider:
  #The next 2 lines specify the python3.10 kernel lambda function in europe
  name: aws
  runtime: python3.10
  region: us-west-2
  # This specify environment variables common to all the lambdas
  environment:
    # This will define an environment variable BUCKET with the name of the bucket created on line 68
    BUCKET:
      Ref: UserBucket
  # This describes the permissions common to all the lambdas
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
          - "*"

# The package tells what should be included and excluded from the zip package
package:
  exclude:
    - venv/**
    - node_modules/**
    - ./**
    - "**/__pycache__/**"
    - "**/*.pyc"
  include:
    - app/**

# This is the configuration of the different lambda function we want to deploy
functions:
  # The homepage function will be triggered on a GET / and will execute the handler function
  homepage:
    handler: app.main.handler
    events:
      - http:
          path: /
          method: GET
  # The user_get function will be triggered on a GET /user/{id} and will execute the user.get function
  user_get:
    handler: app.main.handler
    events:
      - http:
          path: api/users/{id}
          method: GET
  # The user_post function will be triggered on a POST /user and will execute the user.post function
  user_post:
    handler: app.main.handler
    events:
      - http:
          path: api/users/
          method: POST
  # The user_delete function will be triggered on a DELETE /user/{id} and will execute the user.delete function
  user_delete:
    handler: app.main.handler
    events:
      - http:
          path: api/users/{id}
          method: DELETE
  # The user_put function will be triggered on a PUT /user/{id} and will execute the user.put function
  user_put:
    handler: app.main.handler
    events:
      - http:
          path: api/users/{id}
          method: PUT
  # The user_list function will be triggered on a GET /user/ and will execute the user.list function
  user_list:
    handler: app.main.handler
    events:
      - http:
          path: api/users/
          method: GET

#This creates an s3 bucket
resources:
  Resources:
    UserBucket:
      Type: AWS::S3::Bucket

# This is th custom config ...
custom:
  # ... for the serverless-python-requirements plugin
  pythonRequirements:
    dockerizePip: True

#This specify the plugins to use
plugins:
  - serverless-python-requirements
